steps:
  - name: ubuntu
    id: 'create_image_spec'
    entrypoint: "bash"
    args:
      - '-c'
      - |
        echo "$_IMAGE_FAMILY"
        echo "$_PROJECT_ID"
        echo "$_IMAGE_ZONE"
        echo "$_SERVICE_ACCOUNT"
        cat <<END>packer.json
        {
          "builders": [
            {
              "image_name": "$_APP_NAME-$SHORT_SHA",
              "type": "googlecompute",
              "project_id": "$_PROJECT_ID",
              "source_image": "$_SOURCE_IMAGE",
              "image_family": "wids-app-image",
              "ssh_username": "ubuntu",
              "zone": "$_IMAGE_ZONE",
              "tags": ["ovo-poc","ssh"],
              "scopes": "https://www.googleapis.com/auth/cloud-platform"
            }
          ],
          "provisioners": [
            {
              "type": "shell",
              "script": "$_STARTUP_SCRIPT_PATH"
            }
          ]
        }
        END


  - name: 'gcr.io/$_PROJECT_ID/packer'
    args:
      - build
      - packer.json

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    id: Update Instance Group with latest image
    args:
    - '-c'
    - |
      InstanceGroupName=$_APP_NAME-mig
      InstanceTemplate=$_APP_NAME-$SHORT_SHA-$(date +%H%M-%d%m%Y)
      gcloud compute instance-templates create ${InstanceTemplate} --image=$_APP_NAME-$SHORT_SHA --image-project=$_PROJECT_ID --network=$_NETWORK_NAME --subnet=$_SUBNET --region $_REGION --scopes cloud-platform --tags="http-server","ssh","allow-http","ovo-poc"
      gcloud beta compute instance-groups managed rolling-action start-update ${InstanceGroupName} --version template=${InstanceTemplate} --region $_REGION
timeout: 20m0s
