steps:
  - name: ubuntu
    args:
      - '-c'
      - |
        echo "$_IMAGE_FAMILY"
        echo "$_PROJECT_ID"
        echo "$_IMAGE_ZONE"
        echo "$_SERVICE_ACCOUNT"
        cat <<END>packer.json
        {
          "builders": [
            {
              "image_name": "$_APP_NAME-$SHORT_SHA",
              "type": "googlecompute",
              "project_id": "$_PROJECT_ID",
              "source_image_family": "$_SOURCE_IMAGE_FAMILY",
              "image_family": "wids-app-image",
              "ssh_username": "ubuntu",
              "zone": "$_IMAGE_ZONE",
              "tags": ["cloud-native-cicd","ssh"],
              "scopes": "https://www.googleapis.com/auth/cloud-platform"
            }
          ],
        "provisioners": [
            {
              "type": "shell",
              "script": "$_STARTUP_SCRIPT_PATH"
            }
          ]
        }
        END
    id: create_image_spec
    entrypoint: bash
  - name: gcr.io/$_PROJECT_ID/packer
    args:
      - build
      - packer.json

  - name: gcr.io/cloud-builders/gcloud
    id: download secret
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        echo test
        gcloud secrets versions access latest --secret=cicd_demo > /root/.ssh/id_github
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: gcr.io/cloud-builders/git
    id: Add Github Key obtained to local env
    entrypoint: bash
    args:
      - '-c'
      - |
        chmod 600 /root/.ssh/id_github

        cat <<EOF >/root/.ssh/config
          Hostname github.com
          IdentityFile /root/.ssh/id_github
        EOF

        echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: gcr.io/cloud-builders/gcloud
    id: Clone Repository
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        git clone git@github.com:${_GITHUB_REPO_USERNAME}/$REPO_NAME && \
        cd $REPO_NAME && \
        git checkout ${_PRODUCTION_CANDIDATE_BRANCH} && \
        git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: gcr.io/cloud-builders/gcloud
    id: This updated the image.info with latest image
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        echo $_APP_NAME-$SHORT_SHA >> image.info && \
        cat image.info
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: gcr.io/cloud-builders/gcloud
    id: Push deployment image for production environment
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cd $REPO_NAME && \
        git add image.info && \
        git commit -m "Latest image $_APP_NAME-$SHORT_SHA Built from commit ${COMMIT_SHA} Author: $(git log --format='%an <%ae>' -n 1 HEAD)" || true && \
        git push origin ${_PRODUCTION_CANDIDATE_BRANCH} && \
        git tag 'release-'${SHORT_SHA} || true && \
        git push origin 'release-'${SHORT_SHA}

    volumes:
      - name: ssh
        path: /root/.ssh
