steps:
  - name: ubuntu
    args:
      - '-c'
      - |
        echo "$_IMAGE_FAMILY"
        echo "$_PROJECT_ID"
        echo "$_IMAGE_ZONE"
        echo "$_SERVICE_ACCOUNT"
        cat <<END>packer.json
        {
          "builders": [
            {
              "image_name": "$_APP_NAME-$SHORT_SHA",
              "type": "googlecompute",
              "project_id": "$_PROJECT_ID",
              "source_image_family": "$_SOURCE_IMAGE_FAMILY",
              "image_family": "wids-app-image",
              "ssh_username": "ubuntu",
              "zone": "$_IMAGE_ZONE",
              "tags": ["cloud-native-cicd","ssh"],
              "scopes": "https://www.googleapis.com/auth/cloud-platform"
            }
          ],
        "provisioners": [
            {
              "type": "shell",
              "script": "$_STARTUP_SCRIPT_PATH"
            }
          ]
        }
        END
    id: create_image_spec
    entrypoint: bash
  - name: gcr.io/$_PROJECT_ID/packer
    args:
      - build
      - packer.json

timeout: 20m0s
